{
 "title": "GitLab Merge Request Analytics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "repository",
    "label": "Repository",
    "query": "label_values(gitlab_merge_requests_total, project)"
   },
   {
    "name": "branch",
    "label": "Branch",
    "query": "label_values(gitlab_mr_info{project=~\"$repository\"}, branch)"
   }
  ]
 },
 "panels": [
  {
   "title": "In Review",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gitlab_mr_time_in_review_hours{project=~\"$repository\",branch=~\"$branch\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Rework",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gitlab_mr_time_in_rework_hours{project=~\"$repository\",branch=~\"$branch\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Rework Done",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gitlab_mr_time_to_complete_hours{project=~\"$repository\",branch=~\"$branch\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Review Time (Hours)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_mr_time_in_review_hours{project=~\"$repository\",branch=~\"$branch\"}",
     "legendFormat": "{{branch}}"
    }
   ]
  },
  {
   "title": "Rework Time (Hours)",
   "type": "stat",
   "gridPos": { "x": 8, "y": 6, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_mr_time_in_rework_hours{project=~\"$repository\",branch=~\"$branch\"}",
     "legendFormat": "{{branch}}"
    }
   ]
  },
  {
   "title": "Total Completion Time (Hours)",
   "type": "stat",
   "gridPos": { "x": 16, "y": 6, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_mr_time_to_complete_hours{project=~\"$repository\",branch=~\"$branch\"}",
     "legendFormat": "{{branch}}"
    }
   ]
  },
  {
   "title": "Merge Request Details",
   "type": "table",
   "gridPos": { "x": 0, "y": 12, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "gitlab_mr_info{project=~\"$repository\",branch=~\"$branch\"}"
    }
   ]
  }
 ]
}